[build-system]
requires = ['setuptools>=42.0',"wheel"]
buid-backend = "setuptools.build-meta"

[tool.pytest.ini_options]
testpaths = [ "test" ]

[tool.mypy]
mypy.path = "src"
ignore_missing_imports = true
