[build-system]
requires = ['setuptools>=42.0',"wheel"]
buid-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [ "tests" ]

[tool.mypy]
my_path = "src"
ignore_missing_imports = true
